---
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-userlist-secret
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: pgbouncer
    app.kubernetes.io/managed-by: provisioner
data:
  userlist.txt: ImFkbWluIiAiYWRtaW5wYXNzd29yZCIK
